name: Build and deploy code
on: [push]

jobs:
    job1:
        environment:
            name: testing
        env:
            DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
            DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
            DATABASE_PORT: ${{secrets.DATABASE_PORT}}
            DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
            DATABASE_NAME: ${{secrets.DATABASE_NAME}}
            SECRET_KEY: ${{secrets.SECRET_KEY}}
            ALGORITHM: ${{secrets.ALGORITHM}}
            ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
        
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
                    POSTGRES_DB: ${{secrets.DATABASE_NAME}}
                ports:
                    - 5432:5432
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        
        runs-on: ubuntu-latest
        steps:
            - name: Pulling git repo
              uses: actions/checkout@v4.2.2
            - name: Set up Python
              uses: actions/setup-python@v5.6.0
              with:
                python-version: '3.13' 
            - name: Update pip
              run: python -m pip install --upgrade pip
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Tests with Pytest
              run: |
                pip install pytest
                pytest



