name: Build and deploy code
on: [push]
jobs:
  job1:
      runs-on: ubuntu-latest
      steps:
        - name: Pulling git repo
          uses: actions/checkout@v4.2.2
        - name: Set up Python
          uses: actions/setup-python@v5.6.0
          with:
            python-version: '3.13' 
        - name: Update pip
          run: python -m pip install --upgrade pip
        - name: Install dependencies
          run: pip install -r requirements.txt



